version: '3'
services:
  # Backend service
  backend:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - JWT_SECRET=your_secret_key
      - NODE_ENV=development
  
  # Frontend service
  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
